### Insere um cliente

POST http://localhost:8080/clientes
Content-Type: application/json

{tia
  "nome": "Matheus",
  "contatos" : [
    {
      "telefone" : "48123",
      "email" : "testandoemail@gmail.com"
    },

    {
      "telefone" : "58123",
      "email" : "retestandoemail@gmail.com"
    }
  ]
}


### Inserir um cliente

POST http://localhost:8080/clientes
Content-Type: application/json

{
  "nome" : "Jurich",
  "contatos" : [
    {
      "telefone" : "8839949",
      "email" : "Matheus@emailteste.com"
    },

    {
      "telefone" : "999999949",
      "email" : "Mafdffs@emailteste.com"
    }
  ]
}


### Inserir um cliente sem contato

POST http://localhost:8080/clientes
Content-Type: application/json

{
  "nome" : "Jamal"
}





### Inserir um contato para o cliente

POST http://localhost:8080/contatos
Content-Type: application/json

{
  "telefone" : "448756",
  "email": "emailAdicionado@gmail.com",
  "clienteId": 2
}


### Listagem de todos os clientes com seus contatos
GET http://localhost:8080/clientes
Content-Type: application/json


### Listagem de um cliente por ID
GET http://localhost:8080/clientes/1/contatos
Content-Type: application/json
